version: '3.8'

services:
  database:
    container_name: database
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: dlp
      MARIADB_USER: user-dlp
      MARIADB_PASSWORD: password-dlp
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 3306:3306
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user-dlp", "--password=password-dlp"]
      start_period: 5s
      interval: 10s
      timeout: 20s
      retries: 5
  
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    ports:
      - 8080:80
    depends_on:
      - database
    restart: unless-stopped
  
  # web:
  #   container_name: web
  #   build: .
  #   ports:
  #     - 80:80
  #   depends_on:
  #     database:
  #       condition: service_healthy
  #   restart: unless-stopped
  #   volumes:
  #     - ./:/var/www:cached,delegated
  #     - ./var:/symfony/var
  #     - ./vendor:/symfony/vendor